export const StockSearchActionTypes = {
  GET_SUGGESTION_LIST_FULFILLED: "@@GET_SUGGESTION_LIST_FULFILLED",
  GET_SUGGESTION_LIST_REJECTED: "@@GET_SUGGESTION_LIST_REJECTED",
  GET_SUGGESTION_LIST: "@@GET_SUGGESTION_LIST",
  SET_SELECTED_FIRMS: "@@SET_SELECTED_FIRMS"
};
